/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.AuditAction;
import com.makrol.teamcity.api.swagger.client.model.RelatedEntities;
import com.makrol.teamcity.api.swagger.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents an audit event including a user and affected entities.
 */
@ApiModel(description = "Represents an audit event including a user and affected entities.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class AuditEvent {
  @SerializedName("id")
  private String id = null;

  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("action")
  private AuditAction action = null;

  @SerializedName("relatedEntities")
  private RelatedEntities relatedEntities = null;

  @SerializedName("user")
  private User user = null;

  public AuditEvent id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AuditEvent timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public AuditEvent comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AuditEvent action(AuditAction action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(value = "")
  public AuditAction getAction() {
    return action;
  }

  public void setAction(AuditAction action) {
    this.action = action;
  }

  public AuditEvent relatedEntities(RelatedEntities relatedEntities) {
    this.relatedEntities = relatedEntities;
    return this;
  }

   /**
   * Get relatedEntities
   * @return relatedEntities
  **/
  @ApiModelProperty(value = "")
  public RelatedEntities getRelatedEntities() {
    return relatedEntities;
  }

  public void setRelatedEntities(RelatedEntities relatedEntities) {
    this.relatedEntities = relatedEntities;
  }

  public AuditEvent user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditEvent auditEvent = (AuditEvent) o;
    return Objects.equals(this.id, auditEvent.id) &&
        Objects.equals(this.timestamp, auditEvent.timestamp) &&
        Objects.equals(this.comment, auditEvent.comment) &&
        Objects.equals(this.action, auditEvent.action) &&
        Objects.equals(this.relatedEntities, auditEvent.relatedEntities) &&
        Objects.equals(this.user, auditEvent.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timestamp, comment, action, relatedEntities, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditEvent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    relatedEntities: ").append(toIndentedString(relatedEntities)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

