/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.CloudInstances;
import com.makrol.teamcity.api.swagger.client.model.CloudProfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents a cloud instance image saved with a profile.
 */
@ApiModel(description = "Represents a cloud instance image saved with a profile.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class CloudImage {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("profile")
  private CloudProfile profile = null;

  @SerializedName("instances")
  private CloudInstances instances = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("agentTypeId")
  private Integer agentTypeId = null;

  @SerializedName("agentPoolId")
  private Integer agentPoolId = null;

  @SerializedName("operatingSystemName")
  private String operatingSystemName = null;

  @SerializedName("locator")
  private String locator = null;

  public CloudImage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CloudImage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CloudImage href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public CloudImage profile(CloudProfile profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  @ApiModelProperty(value = "")
  public CloudProfile getProfile() {
    return profile;
  }

  public void setProfile(CloudProfile profile) {
    this.profile = profile;
  }

  public CloudImage instances(CloudInstances instances) {
    this.instances = instances;
    return this;
  }

   /**
   * Get instances
   * @return instances
  **/
  @ApiModelProperty(value = "")
  public CloudInstances getInstances() {
    return instances;
  }

  public void setInstances(CloudInstances instances) {
    this.instances = instances;
  }

  public CloudImage errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public CloudImage agentTypeId(Integer agentTypeId) {
    this.agentTypeId = agentTypeId;
    return this;
  }

   /**
   * Get agentTypeId
   * @return agentTypeId
  **/
  @ApiModelProperty(value = "")
  public Integer getAgentTypeId() {
    return agentTypeId;
  }

  public void setAgentTypeId(Integer agentTypeId) {
    this.agentTypeId = agentTypeId;
  }

  public CloudImage agentPoolId(Integer agentPoolId) {
    this.agentPoolId = agentPoolId;
    return this;
  }

   /**
   * Get agentPoolId
   * @return agentPoolId
  **/
  @ApiModelProperty(value = "")
  public Integer getAgentPoolId() {
    return agentPoolId;
  }

  public void setAgentPoolId(Integer agentPoolId) {
    this.agentPoolId = agentPoolId;
  }

  public CloudImage operatingSystemName(String operatingSystemName) {
    this.operatingSystemName = operatingSystemName;
    return this;
  }

   /**
   * Get operatingSystemName
   * @return operatingSystemName
  **/
  @ApiModelProperty(value = "")
  public String getOperatingSystemName() {
    return operatingSystemName;
  }

  public void setOperatingSystemName(String operatingSystemName) {
    this.operatingSystemName = operatingSystemName;
  }

  public CloudImage locator(String locator) {
    this.locator = locator;
    return this;
  }

   /**
   * Get locator
   * @return locator
  **/
  @ApiModelProperty(value = "")
  public String getLocator() {
    return locator;
  }

  public void setLocator(String locator) {
    this.locator = locator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudImage cloudImage = (CloudImage) o;
    return Objects.equals(this.id, cloudImage.id) &&
        Objects.equals(this.name, cloudImage.name) &&
        Objects.equals(this.href, cloudImage.href) &&
        Objects.equals(this.profile, cloudImage.profile) &&
        Objects.equals(this.instances, cloudImage.instances) &&
        Objects.equals(this.errorMessage, cloudImage.errorMessage) &&
        Objects.equals(this.agentTypeId, cloudImage.agentTypeId) &&
        Objects.equals(this.agentPoolId, cloudImage.agentPoolId) &&
        Objects.equals(this.operatingSystemName, cloudImage.operatingSystemName) &&
        Objects.equals(this.locator, cloudImage.locator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, href, profile, instances, errorMessage, agentTypeId, agentPoolId, operatingSystemName, locator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudImage {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    instances: ").append(toIndentedString(instances)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    agentTypeId: ").append(toIndentedString(agentTypeId)).append("\n");
    sb.append("    agentPoolId: ").append(toIndentedString(agentPoolId)).append("\n");
    sb.append("    operatingSystemName: ").append(toIndentedString(operatingSystemName)).append("\n");
    sb.append("    locator: ").append(toIndentedString(locator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

