/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.Permission;
import com.makrol.teamcity.api.swagger.client.model.Project;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents permission restrictions of an authentication token.
 */
@ApiModel(description = "Represents permission restrictions of an authentication token.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class PermissionRestriction {
  @SerializedName("isGlobalScope")
  private Boolean isGlobalScope = null;

  @SerializedName("project")
  private Project project = null;

  @SerializedName("permission")
  private Permission permission = null;

  public PermissionRestriction isGlobalScope(Boolean isGlobalScope) {
    this.isGlobalScope = isGlobalScope;
    return this;
  }

   /**
   * Get isGlobalScope
   * @return isGlobalScope
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsGlobalScope() {
    return isGlobalScope;
  }

  public void setIsGlobalScope(Boolean isGlobalScope) {
    this.isGlobalScope = isGlobalScope;
  }

  public PermissionRestriction project(Project project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(value = "")
  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public PermissionRestriction permission(Permission permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  @ApiModelProperty(value = "")
  public Permission getPermission() {
    return permission;
  }

  public void setPermission(Permission permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionRestriction permissionRestriction = (PermissionRestriction) o;
    return Objects.equals(this.isGlobalScope, permissionRestriction.isGlobalScope) &&
        Objects.equals(this.project, permissionRestriction.project) &&
        Objects.equals(this.permission, permissionRestriction.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isGlobalScope, project, permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionRestriction {\n");
    
    sb.append("    isGlobalScope: ").append(toIndentedString(isGlobalScope)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

