/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.Plugin;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a list of Plugin entities.
 */
@ApiModel(description = "Represents a list of Plugin entities.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class Plugins {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("plugin")
  private List<Plugin> plugin = null;

  public Plugins count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public Plugins plugin(List<Plugin> plugin) {
    this.plugin = plugin;
    return this;
  }

  public Plugins addPluginItem(Plugin pluginItem) {
    if (this.plugin == null) {
      this.plugin = new ArrayList<Plugin>();
    }
    this.plugin.add(pluginItem);
    return this;
  }

   /**
   * Get plugin
   * @return plugin
  **/
  @ApiModelProperty(value = "")
  public List<Plugin> getPlugin() {
    return plugin;
  }

  public void setPlugin(List<Plugin> plugin) {
    this.plugin = plugin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plugins plugins = (Plugins) o;
    return Objects.equals(this.count, plugins.count) &&
        Objects.equals(this.plugin, plugins.plugin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, plugin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plugins {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

