/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.Problems;
import com.makrol.teamcity.api.swagger.client.model.Tests;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents an investigation target.
 */
@ApiModel(description = "Represents an investigation target.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class ProblemTarget {
  @SerializedName("anyProblem")
  private Boolean anyProblem = null;

  @SerializedName("tests")
  private Tests tests = null;

  @SerializedName("problems")
  private Problems problems = null;

  public ProblemTarget anyProblem(Boolean anyProblem) {
    this.anyProblem = anyProblem;
    return this;
  }

   /**
   * Get anyProblem
   * @return anyProblem
  **/
  @ApiModelProperty(value = "")
  public Boolean isAnyProblem() {
    return anyProblem;
  }

  public void setAnyProblem(Boolean anyProblem) {
    this.anyProblem = anyProblem;
  }

  public ProblemTarget tests(Tests tests) {
    this.tests = tests;
    return this;
  }

   /**
   * Get tests
   * @return tests
  **/
  @ApiModelProperty(value = "")
  public Tests getTests() {
    return tests;
  }

  public void setTests(Tests tests) {
    this.tests = tests;
  }

  public ProblemTarget problems(Problems problems) {
    this.problems = problems;
    return this;
  }

   /**
   * Get problems
   * @return problems
  **/
  @ApiModelProperty(value = "")
  public Problems getProblems() {
    return problems;
  }

  public void setProblems(Problems problems) {
    this.problems = problems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProblemTarget problemTarget = (ProblemTarget) o;
    return Objects.equals(this.anyProblem, problemTarget.anyProblem) &&
        Objects.equals(this.tests, problemTarget.tests) &&
        Objects.equals(this.problems, problemTarget.problems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anyProblem, tests, problems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProblemTarget {\n");
    
    sb.append("    anyProblem: ").append(toIndentedString(anyProblem)).append("\n");
    sb.append("    tests: ").append(toIndentedString(tests)).append("\n");
    sb.append("    problems: ").append(toIndentedString(problems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

