/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.Build;
import com.makrol.teamcity.api.swagger.client.model.BuildType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SnapshotDependencyLink
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class SnapshotDependencyLink {
  @SerializedName("build")
  private Build build = null;

  @SerializedName("buildType")
  private BuildType buildType = null;

  @SerializedName("buildTypeBranch")
  private String buildTypeBranch = null;

  public SnapshotDependencyLink build(Build build) {
    this.build = build;
    return this;
  }

   /**
   * Get build
   * @return build
  **/
  @ApiModelProperty(value = "")
  public Build getBuild() {
    return build;
  }

  public void setBuild(Build build) {
    this.build = build;
  }

  public SnapshotDependencyLink buildType(BuildType buildType) {
    this.buildType = buildType;
    return this;
  }

   /**
   * Get buildType
   * @return buildType
  **/
  @ApiModelProperty(value = "")
  public BuildType getBuildType() {
    return buildType;
  }

  public void setBuildType(BuildType buildType) {
    this.buildType = buildType;
  }

  public SnapshotDependencyLink buildTypeBranch(String buildTypeBranch) {
    this.buildTypeBranch = buildTypeBranch;
    return this;
  }

   /**
   * Get buildTypeBranch
   * @return buildTypeBranch
  **/
  @ApiModelProperty(value = "")
  public String getBuildTypeBranch() {
    return buildTypeBranch;
  }

  public void setBuildTypeBranch(String buildTypeBranch) {
    this.buildTypeBranch = buildTypeBranch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnapshotDependencyLink snapshotDependencyLink = (SnapshotDependencyLink) o;
    return Objects.equals(this.build, snapshotDependencyLink.build) &&
        Objects.equals(this.buildType, snapshotDependencyLink.buildType) &&
        Objects.equals(this.buildTypeBranch, snapshotDependencyLink.buildTypeBranch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(build, buildType, buildTypeBranch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnapshotDependencyLink {\n");
    
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    buildType: ").append(toIndentedString(buildType)).append("\n");
    sb.append("    buildTypeBranch: ").append(toIndentedString(buildTypeBranch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

