/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.makrol.teamcity.api.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.makrol.teamcity.api.swagger.client.model.VcsRoot;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents a VCS root assigned to this build configuration.
 */
@ApiModel(description = "Represents a VCS root assigned to this build configuration.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-14T01:07:21.722+03:00")
public class VcsRootEntry {
  @SerializedName("id")
  private String id = null;

  @SerializedName("inherited")
  private Boolean inherited = null;

  @SerializedName("vcs-root")
  private VcsRoot vcsRoot = null;

  @SerializedName("checkout-rules")
  private String checkoutRules = null;

  public VcsRootEntry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VcsRootEntry inherited(Boolean inherited) {
    this.inherited = inherited;
    return this;
  }

   /**
   * Get inherited
   * @return inherited
  **/
  @ApiModelProperty(value = "")
  public Boolean isInherited() {
    return inherited;
  }

  public void setInherited(Boolean inherited) {
    this.inherited = inherited;
  }

  public VcsRootEntry vcsRoot(VcsRoot vcsRoot) {
    this.vcsRoot = vcsRoot;
    return this;
  }

   /**
   * Get vcsRoot
   * @return vcsRoot
  **/
  @ApiModelProperty(value = "")
  public VcsRoot getVcsRoot() {
    return vcsRoot;
  }

  public void setVcsRoot(VcsRoot vcsRoot) {
    this.vcsRoot = vcsRoot;
  }

  public VcsRootEntry checkoutRules(String checkoutRules) {
    this.checkoutRules = checkoutRules;
    return this;
  }

   /**
   * Get checkoutRules
   * @return checkoutRules
  **/
  @ApiModelProperty(value = "")
  public String getCheckoutRules() {
    return checkoutRules;
  }

  public void setCheckoutRules(String checkoutRules) {
    this.checkoutRules = checkoutRules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VcsRootEntry vcsRootEntry = (VcsRootEntry) o;
    return Objects.equals(this.id, vcsRootEntry.id) &&
        Objects.equals(this.inherited, vcsRootEntry.inherited) &&
        Objects.equals(this.vcsRoot, vcsRootEntry.vcsRoot) &&
        Objects.equals(this.checkoutRules, vcsRootEntry.checkoutRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, inherited, vcsRoot, checkoutRules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VcsRootEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inherited: ").append(toIndentedString(inherited)).append("\n");
    sb.append("    vcsRoot: ").append(toIndentedString(vcsRoot)).append("\n");
    sb.append("    checkoutRules: ").append(toIndentedString(checkoutRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

